### ISSUE TITLE
params[:otp_code_token] not being passed to config.auth.authenticate

### ISSUE THREAD

**Issue by Alxzu** [McRipper/trestle-auth-otp#1]
Hi, I'm trying to implement this on a new project but I'm always getting the same error "invalid credentials". When I debug the initializer I noticed that `params[:otp_code_token]` is nil.

![Screen Shot 2020-06-27 at 13 51 40](https://user-images.githubusercontent.com/8084303/85927579-7ca78e80-b87d-11ea-8ed5-9c1625ae0fbd.png)
![Screen Shot 2020-06-27 at 13 53 14](https://user-images.githubusercontent.com/8084303/85927594-8df09b00-b87d-11ea-974f-c0956163b19a.png)

Do I need to set up anything else? 

Great gem btw, thanks

Rails: 6.03
Ruby: 2.6.3

![Screen Shot 2020-06-27 at 13 55 16](https://user-images.githubusercontent.com/8084303/85927641-d8721780-b87d-11ea-90fa-8c0e7e4b35cf.png)

**Comment by McRipper** [comment]
Hi @Alxzu, please update to the latest version of this library '0.2.1' and use the head branch of 'trestle-auth' until a new version is published by the author.

```
gem 'trestle-auth', '~> 0.4.0', github: 'TrestleAdmin/trestle-auth'
```
